### ISSUE TITLE
k3s_quickstart cannot run docker image

### ISSUE THREAD

**Issue by hubbertsmith** [hubbertsmith/anu-i4ops#20]
k3s_quickstart -- u9 -- 172.26.37.189  (zerotier access) -- anu -- anupass

**>>> i4test.yaml**
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: c9e3606dbb0f      <<< this imageID is listed with '$ docker images'   it is checked
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10

**>> the command**  
 kk apply -f i4test.yaml 
deployment.apps/my-app-deployment created

>> the results
--- pods --- 
NAMESPACE     NAME                                       READY   STATUS         RESTARTS      AGE
kube-system   helm-install-traefik-crd-q6wkf             0/1     Completed      0             53m
kube-system   helm-install-traefik-cwpkv                 0/1     Completed      0             53m
kube-system   local-path-provisioner-957fdf8bc-lm2wz     1/1     Running        1 (26m ago)   53m
kube-system   kube-vip-ds-nlg2d                          1/1     Running        2 (26m ago)   53m
kube-system   coredns-77ccd57875-bs6l2                   1/1     Running        1 (26m ago)   53m
kube-system   kube-vip-cloud-provider-54c878b6c5-7phqx   1/1     Running        2 (26m ago)   53m
kube-system   traefik-64f55bb67d-sgjtl                   1/1     Running        1 (26m ago)   52m
kube-system   metrics-server-648b5df564-4ddkt            1/1     Running        1 (26m ago)   53m
default       my-app-deployment-86785cc594-kw47f         0/1     ErrImagePull   0             31s      << not starting

 --- namespaces -- 
NAME              STATUS   AGE
kube-system       Active   54m
default           Active   54m
kube-public       Active   54m
kube-node-lease   Active   54m
--- deployments --- 
NAMESPACE     NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   kube-vip-cloud-provider   1/1     1            1           54m
kube-system   local-path-provisioner    1/1     1            1           54m
kube-system   coredns                   1/1     1            1           54m
kube-system   traefik                   1/1     1            1           52m
kube-system   metrics-server            1/1     1            1           54m
default       my-app-deployment         0/1     1            0           31s    << not starting

**Comment by Annuore** [comment]
can you add the content of i4.yaml?

**Comment by hubbertsmith** [comment]
i4test.yaml is included above
there is no i4.yaml.
what am I missing?
thanks so much for the help

**Comment by Annuore** [comment]
My bad. I didn't pay attention to it. The image should be referenced with the repository and tag like repository:tag not with the hash. Is that how you referenced it or it was changed somehow? Also make sure that the image is not in a private repository, else you'll need to configure access to the image using secrets

**Comment by hubbertsmith** [comment]
I'll try again in the am.
With the name:tag and provide exact results.

**Comment by hubbertsmith** [comment]
summary -  same result using i4docker:latest

review local docker images
$ docker images
i4docker                     latest        c9e3606dbb0f   2 days ago    3.4GB

kk apply -f i4test.yaml   >>> using --  c9e3606dbb0f   
deployment.apps/my-app-deployment created
get pods
default       my-app-deployment-86785cc594-jcrb2         0/1     ErrImagePull   0             3s   <<< doesnt start


kk apply -f i4test.yaml     >>> using --  i4docker:latest
deployment.apps/my-app-deployment created
get pods
default       my-app-deployment-5ff5845df8-wkfrz         0/1     ErrImagePull   0             38s

**Comment by Annuore** [comment]
Run a kk describe on the pod to get the events. Have you pushed this image to dockerhub?
Also, you'll likely need to add your username to the image reference like username/repo:tag

**Comment by hubbertsmith** [comment]
hey, thanks, will do
does this mean the docker image _must_ be pulled from repository?
I've been doing docker local images, is this OK?

I will try it as you suggest


***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
Inspiring Remote Tech Teams
<https://www.amazon.com/Inspiring-Remote-Tech-Teams-Performance-ebook/dp/B08VLFYTT3/ref=sr_1_1?crid=H8M90B2UMA6Q&dchild=1&keywords=hubbert+smith&qid=1624635961&sprefix=hubbert+s%2Caps%2C209&sr=8-1>
*Linkedin Learning: Program Management for IT Professionals
<https://tinyurl.com/y8rzzzoa>*
Blog - hubbertsmith.com <http://hubbertsmith.com>
Schedule a MEETING <https://calendly.com/hubbert/60min>

**Comment by hubbertsmith** [comment]
root@u9:/i4/testegress# kk get pods
NAME                                 READY   STATUS             RESTARTS   AGE
my-app-deployment-5ff5845df8-wkfrz   0/1     ImagePullBackOff   0          4h3m

root@u9:/i4/testegress# kk describe my-app-deployment-5ff5845df8-wkfrz
error: the server doesn't have a resource type "my-app-deployment-5ff5845df8-wkfrz"

**Comment by hubbertsmith** [comment]
success = run ANY docker image, ubuntu:latest is fine, we can go from there

**Comment by Annuore** [comment]
> root@u9:/i4/testegress# kk get pods NAME READY STATUS RESTARTS AGE my-app-deployment-5ff5845df8-wkfrz 0/1 ImagePullBackOff 0 4h3m
> 
> root@u9:/i4/testegress# kk describe my-app-deployment-5ff5845df8-wkfrz error: the server doesn't have a resource type "my-app-deployment-5ff5845df8-wkfrz"

you have to add pod and in kk describe pod my-app-deployment-5ff5845df8-wkfrz

**Comment by Annuore** [comment]
> success = run ANY docker image, ubuntu:latest is fine, we can go from there
> 
> kk apply -f i4test.yaml >>> using ubuntu:latest deployment.apps/my-app-deployment created get pods default my-app-deployment-7d49cd8884-b8qkv 0/1 CrashLoopBackOff 1 (11s ago) 17s <<< doesnt start

The probes are going to cause it to fail because the health check path likely doesn't exist or isn't configured there on ubuntu and so you have to take out the probes and add command under spec.template.spec.containers else the ubuntu container will exit immediately because the ubuntu shell expects a command.

**Comment by hubbertsmith** [comment]
hiya, thanks for the response

I see probes yaml file (I commented them out, yaml file attached)
and I appended kk describe pod  my-app-deployment-7d675d87f9-lgf4t

I ran it with ubuntu:latest
same behavior --
--- pods ---
NAMESPACE     NAME                                       READY   STATUS
     RESTARTS       AGE
kube-system   helm-install-traefik-crd-q6wkf             0/1     Completed
  0              2d4h
kube-system   helm-install-traefik-cwpkv                 0/1     Completed
  0              2d4h
kube-system   local-path-provisioner-957fdf8bc-lm2wz     1/1     Running
    1 (2d3h ago)   2d4h
kube-system   kube-vip-ds-nlg2d                          1/1     Running
    2 (2d3h ago)   2d4h
kube-system   coredns-77ccd57875-bs6l2                   1/1     Running
    1 (2d3h ago)   2d4h
kube-system   kube-vip-cloud-provider-54c878b6c5-7phqx   1/1     Running
    2 (2d3h ago)   2d4h
kube-system   traefik-64f55bb67d-sgjtl                   1/1     Running
    1 (2d3h ago)   2d4h
kube-system   metrics-server-648b5df564-4ddkt            1/1     Running
    1 (2d3h ago)   2d4h
default       my-app-deployment-7d675d87f9-lgf4t         0/1     Completed
  2 (20s ago)    23s
kk describe pod ubuntu-deployment-74f4fcdd7-456xj
--- namespaces --
NAME              STATUS   AGE
kube-system       Active   2d4h
default           Active   2d4h
kube-public       Active   2d4h
kube-node-lease   Active   2d4h
--- deployments ---
NAMESPACE     NAME                      READY   UP-TO-DATE   AVAILABLE
  AGE
kube-system   kube-vip-cloud-provider   1/1     1            1
          2d4h
kube-system   local-path-provisioner    1/1     1            1
          2d4h
kube-system   coredns                   1/1     1            1
          2d4h
kube-system   traefik                   1/1     1            1
          2d4h
kube-system   metrics-server            1/1     1            1
          2d4h
default       my-app-deployment         0/1     1            0           23s

========================================================

***@***.***:/home/hubbert/anu-i4ops-k3s/k3s_quickstart# kk describe pod
my-app-deployment-7d675d87f9-lgf4t
Name:             my-app-deployment-7d675d87f9-lgf4t
Namespace:        default
Priority:         0
Service Account:  default
Node:             u9/192.168.1.187
Start Time:       Fri, 18 Aug 2023 12:30:11 -0600
Labels:           app=my-app
                 pod-template-hash=7d675d87f9
Annotations:      <none>
Status:           Running
IP:               10.42.0.11
IPs:
 IP:           10.42.0.11
Controlled By:  ReplicaSet/my-app-deployment-7d675d87f9
Containers:
 my-app:
   Container ID:
  containerd://dab1cb970b06e1d5bc51bff3d9984e719079b523250b0e649685c57fa4467863

   Image:          ubuntu:latest
   Image ID:
***@***.***:ec050c32e4a6085b423d36ecd025c0d3ff00c38ab93a3d71a460ff1c44fa6d77
   Port:           80/TCP
   Host Port:      0/TCP
   State:          Waiting
     Reason:       CrashLoopBackOff
   Last State:     Terminated
     Reason:       Completed
     Exit Code:    0
     Started:      Fri, 18 Aug 2023 12:31:48 -0600
     Finished:     Fri, 18 Aug 2023 12:31:48 -0600
   Ready:          False
   Restart Count:  4
   Limits:
     cpu:     500m
     memory:  128Mi
   Requests:
     cpu:        250m
     memory:     64Mi
   Environment:  <none>
   Mounts:
     /var/run/secrets/kubernetes.io/serviceaccount from
kube-api-access-95tqt (ro)
Conditions:
 Type              Status
 Initialized       True
 Ready             False
 ContainersReady   False
 PodScheduled      True
Volumes:
 kube-api-access-95tqt:
   Type:                    Projected (a volume that contains injected data
from multiple sources)
   TokenExpirationSeconds:  3607
   ConfigMapName:           kube-root-ca.crt
   ConfigMapOptional:       <nil>
   DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute
op=Exists for 300s
                            node.kubernetes.io/unreachable:NoExecute
op=Exists for 300s
Events:
 Type     Reason     Age                   From               Message
 ----     ------     ----                  ----               -------
 Normal   Scheduled  2m51s                 default-scheduler  Successfully
assigned default/my-app-deployment-7d675d87f9-lgf4t to u9
 Normal   Pulled     2m50s                 kubelet            Successfully
pulled image "ubuntu:latest" in 643.941399ms (643.955297ms including
waiting)
 Normal   Pulled     2m49s                 kubelet            Successfully
pulled image "ubuntu:latest" in 631.886748ms (631.90377ms including
waiting)
 Normal   Pulled     2m33s                 kubelet            Successfully
pulled image "ubuntu:latest" in 622.358575ms (622.375508ms including
waiting)
 Normal   Pulled     2m7s                  kubelet            Successfully
pulled image "ubuntu:latest" in 654.982853ms (654.997302ms including
waiting)
 Normal   Created    2m7s (x4 over 2m50s)  kubelet            Created
container my-app
 Normal   Started    2m7s (x4 over 2m50s)  kubelet            Started
container my-app
 Warning  BackOff    88s (x8 over 2m49s)   kubelet            Back-off
restarting failed container my-app in pod
my-app-deployment-7d675d87f9-lgf4t_default(ee8255f3-42e1-4103-8b1e-
54d1c3fd70e3)
 Normal   Pulling    74s (x5 over 2m51s)   kubelet            Pulling image
"ubuntu:latest"




***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
Inspiring Remote Tech Teams
<https://www.amazon.com/Inspiring-Remote-Tech-Teams-Performance-ebook/dp/B08VLFYTT3/ref=sr_1_1?crid=H8M90B2UMA6Q&dchild=1&keywords=hubbert+smith&qid=1624635961&sprefix=hubbert+s%2Caps%2C209&sr=8-1>
*Linkedin Learning: Program Management for IT Professionals
<https://tinyurl.com/y8rzzzoa>*
Blog - hubbertsmith.com <http://hubbertsmith.com>
Schedule a MEETING <https://calendly.com/hubbert/60min>

**Comment by hubbertsmith** [comment]
I am unclear what to do with this ...
and add command under spec.template.spec.containers else the ubuntu
container will exit immediately because the ubuntu shell expects a command.

thanks for your help and patience


***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
Inspiring Remote Tech Teams
<https://www.amazon.com/Inspiring-Remote-Tech-Teams-Performance-ebook/dp/B08VLFYTT3/ref=sr_1_1?crid=H8M90B2UMA6Q&dchild=1&keywords=hubbert+smith&qid=1624635961&sprefix=hubbert+s%2Caps%2C209&sr=8-1>
*Linkedin Learning: Program Management for IT Professionals
<https://tinyurl.com/y8rzzzoa>*
Blog - hubbertsmith.com <http://hubbertsmith.com>
Schedule a MEETING <https://calendly.com/hubbert/60min>
