### ISSUE TITLE
k3_squickstart README.md -- deploy.yaml error

### ISSUE THREAD

**Issue by hubbertsmith** [hubbertsmith/anu-i4ops#29]
/home/i4demo/deployment.yaml (file attached)

>>> here is the error >>>> 
$ kubectl apply -f deploy.yaml
deployment.apps/nginx-dep configured
The Service "nginx-svc" is invalid: spec.type: Unsupported value: "clusterIP": supported values: "ClusterIP", "ExternalName", "LoadBalancer", "NodePort

>>>> here is what kubectl shows
kk get deployments
NAME                                  READY   UP-TO-DATE   AVAILABLE   AGE
my-release-nginx-ingress-controller   1/1     1            1           3h3m
      nginx-dep                             2/2     2                    2           5m34s

the README says
[Sample deployment](https://github.com/hubbertsmith/anu-i4ops/tree/k3s/k3s_quickstart#sample-deployment)
On the user's home directory, find a [deploy.yaml](https://github.com/hubbertsmith/anu-i4ops/tree/k3s/k3s_quickstart#roles/install/templates/deploy.yaml.j2) file
    Change the image reference under spec.template.spec.containers to your image.
    Run kubectl apply -f deploy.yaml. This will create two replicas of nginx deployment and a service.
    kubectl get deployments
    kubectl delete -f deployment.yaml

**Comment by Annuore** [comment]
Change the line with clusterIP to ClusterIP. It's under the service definition. That's a typo. I have updated it in the code itself, maybe you can do pull again
