### ISSUE TITLE
virtctl start testvm -- stuck at pending --- I am missing a step to create PVC

### ISSUE THREAD

**Issue by hubbertsmith** [hubbertsmith/anu-i4ops#31]
root@u5:/home/i4demo# virtctl start testvm
VM testvm was scheduled to start
root@u5:/home/i4demo# kk get vm,vmi
NAME                                AGE   STATUS             READY
virtualmachine.kubevirt.io/testvm   47s   ErrorPvcNotFound   False

NAME                                        AGE   PHASE     IP    NODENAME   READY
virtualmachineinstance.kubevirt.io/testvm   16s   Pending                    False
root@u5:/home/i4demo# kk get vm,vmi
NAME                                AGE   STATUS             READY
virtualmachine.kubevirt.io/testvm   83s   ErrorPvcNotFound   False

NAME                                        AGE   PHASE     IP    NODENAME   READY
virtualmachineinstance.kubevirt.io/testvm   52s   Pending                    False
root@u5:/home/i4demo# kk get vm,vmi
NAME                                AGE   STATUS             READY
virtualmachine.kubevirt.io/testvm   47m   ErrorPvcNotFound   False

NAME                                        AGE   PHASE     IP    NODENAME   READY
virtualmachineinstance.kubevirt.io/testvm   47m   Pending                    False

**Comment by Annuore** [comment]
here's a link to that. https://github.com/Annuore/anu-i4ops/tree/k3s/kubevirt#to-use-the-newly-deployed-longhorn-on-the-remote-host

**Comment by hubbertsmith** [comment]
there is no file with that name

cd ~/longhorn
kubectl apply -f longhorn-vm-pvc.yaml


***@***.*** | 385 321 0757 | LinkedIN
<https://www.linkedin.com/in/hubbertsmith/>
Inspiring Remote Tech Teams
<https://www.amazon.com/Inspiring-Remote-Tech-Teams-Performance-ebook/dp/B08VLFYTT3/ref=sr_1_1?crid=H8M90B2UMA6Q&dchild=1&keywords=hubbert+smith&qid=1624635961&sprefix=hubbert+s%2Caps%2C209&sr=8-1>
*Linkedin Learning: Program Management for IT Professionals
<https://tinyurl.com/y8rzzzoa>*
Blog - hubbertsmith.com <http://hubbertsmith.com>
Schedule a MEETING <https://calendly.com/hubbert/60min>

**Comment by Annuore** [comment]
It's not contained in the repo that you cloned. It's on the host that's running the cluster, if you're running the k3s_quickstart  cluster on u5 for example, It's gonna be on u5.

**Comment by hubbertsmith** [comment]
Hey. I looked on u5. Did not find
That yaml.

**Comment by Annuore** [comment]
where do you have the cluster running? Did you run the longhorn playbook already? It's not gonna be on there if you don't run the longhorn playbook that installs it in the cluster

**Comment by hubbertsmith** [comment]
I found it.
/home/i4demo/longhorn

**Comment by hubbertsmith** [comment]
I'm going to update the longhorn readme
Ok?
